Feature/tm-tasks
owlscatcher/TaskManager pull request #16
Opened 2021-11-27 12:18 UTC by owlscatcher

2021-11-29 19:59 UTC, greybutton requested changes

2021-11-29 19:59 UTC, greybutton commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +        {count !== totalCount ? (
`count !== totalCount && (` можно так, чтобы `: null` не делать

2021-11-29 19:59 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import ColumnHeader from '../ColumnHeader';
import ColumnHeader from 'components/ColumnHeader';

2021-11-29 19:59 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import AddPopup from '../AddPopup';
import AddPopup from 'components/AddPopup';

2021-11-29 19:59 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import TaskForm from '../../forms/TaskForm';
import TaskForm from 'forms/TaskForm';

2021-11-29 20:13 UTC, owlscatcher commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +        {count !== totalCount ? (
> 

Учел, спасибо!

2021-11-30 07:03 UTC, greybutton approved these changes

2021-11-30 07:04 UTC, merged