Feature/generating-controllers
owlscatcher/TaskManager pull request #8
Opened 2021-10-14 08:10 UTC by owlscatcher

* Board and Session controllers has been generated (also install webpack from fix error in tests);
* MDL has been installed;
* MDL style has been added.

2021-10-14 18:59 UTC, greybutton requested changes
где установка гема slim-rails?

2021-10-14 19:30 UTC, owlscatcher commented
> где установка гема slim-rails?

Я его сразу залил в develop https://github.com/owlscatcher/TaskManager/commit/cfe50d95ed6c8b3978914be12f9f58d1d5ba9bc3. В задании не говорилось о том, что нужно включить это изменение в коммит, я и подумал, что его не обязательно отражать в пулл реквесте, это же просто установка гема.

![image](https://user-images.githubusercontent.com/46975515/137385479-0ebd9fff-d50e-49f9-b779-1d9632faa072.png)

Это нужно исправлять или можно оставить всё как есть?

2021-10-16 09:14 UTC, greybutton approved these changes
Хорошо, исправлять не нужно, оставь как есть. Но в следующий раз не мерджи фича ветки друг в друга. В данном случае нужно было дождаться аппрува feature/generating-controllers и после этого мержить ветки по порядку в develop

2021-10-16 09:15 UTC, owlscatcher commented
> Хорошо, исправлять не нужно, оставь как есть. Но в следующий раз не мерджи фича ветки друг в друга. В данном случае нужно было дождаться аппрува feature/generating-controllers и после этого мержить ветки по порядку в develop

Понял! Большое спасибо!

2021-10-16 09:16 UTC, merged